language: node_js
node_js:
  - 12
cache:
  directories:
  - node_modules
script:
  - npm run build
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: out
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|main)$
env: 
  CI: false
